### PR TITLE
Homework2

### PR DESCRIPTION
**Pull request by CilgaIscan**

### CODE REVIEW

**Comment by AaronMqz** [comment]
hi,

the S3 url: 'https://cilga-aws-course-spa.s3.eu-central-1.amazonaws.com' is not configured the access policy correctly to show '403 access denied' error.

**Comment by CilgaIscan** [comment]
Hi, @AaronMqz! I shared wrong path sorry. The correct path is: https://cilga-aws-course-spa.s3.eu-central-1.amazonaws.com/index.html

**Comment by AaronMqz** [comment]
hi, 

This url 'https://cilga-aws-course-spa.s3.eu-central-1.amazonaws.com/index.html' corresponds only to the index.html file, the missing 'S3-website' url should have something like this, example: 

https://[bucket-name].**s3-website-**[region].amazonaws.com 
(the /index.html is not necessary).

you can find that  website url in S3 properties and at the bottom you should find something like 'Static Website Hosting'

**Comment by CilgaIscan** [comment]
http://cilga-aws-course-spa.s3-website.eu-central-1.amazonaws.com I guess this is correct. It was enabled but I did not add this link

**Pull request merged**
